### ISSUE TITLE
ftplugin can be improve

### ISSUE THREAD

**Issue by mike325** [jakemason/ouroboros#1]
```viml
if exists("g:loaded_ouroboros")
    finish
endif
let g:loaded_ouroboros = 1
```
ftplugins are source every time a corresponding filetype it is useful to set local options or local commands having a global control variable prevents this.

```viml
command! -buffer -nargs=0 Ouroboros lua ouroboros.list()
```
commands should be enable in their corresponding scopes, global if they works across multiple buffers or local if they are expected to work only in the local buffer

**Comment by jakemason** [comment]
Hi Mike,

I'm assuming that for this item you were looking at the dev branch:

https://github.com/jakemason/ouroboros/tree/dev

Where do I still need this code?:
```viml
if exists("g:loaded_ouroboros")
    finish
endif
let g:loaded_ouroboros = 1
```

I believe I've already got a load guard in c.vim/cpp.vim and have had one from early on -- am I missing it elsewhere? I thought that these were the only files that needed it as they are the ones that are sourced first.

The second suggestion about registering the command as local to a buffer is a great one. I'll make that change soon.|

Thanks,
Jake

**Comment by mike325** [comment]
Yes, sorry I forgot to mention this is from the dev branch.

You don't need it if you migrate to ftplugin, that type of safe guard is meant to be used in `plugin/` to avoid re-sourcing after the startup, `ftplugin/` is meant to be source every time you open the corresponding filetype because it will set local options/commands/mappings.

**Comment by jakemason** [comment]
Thanks for this suggestion Mike, this should now be merged into master. It works well on my end, but please let me know if you have any problems.
