### ISSUE TITLE
Error when trying to create file

### ISSUE THREAD

**Issue by smitropoulos** [jakemason/ouroboros#10]
Hey

Trying to create a file, I am getting an error thrown that reads:

```
Error: E5108: Error executing lua Vim:E739: Cannot create directory /XXXXXXXXXX/cppcache/src: file already exists
stack traceback:
	[C]: in function 'mkdir'
	.../.local/share/nvim/lazy/ouroboros/lua/ouroboros/init.lua:86: in function 'on_confirm'
	/usr/share/nvim/runtime/lua/vim/ui.lua:103: in function 'input'
	.../.local/share/nvim/lazy/ouroboros/lua/ouroboros/init.lua:81: in function 'switch'
	[string ":lua"]:1: in main chunk
```

I noticed in the switch function, you have an extra `-` I think `vim.fn.mkdir(path, "-p")`

In the neovim docs they do not https://neovim.io/doc/user/builtin.html#E739

**Comment by jakemason** [comment]
Hey, looks like you're right. I haven't run into this myself yet (maybe an OS-dependent thing) but I just merged #7 which should solve this.
