### ISSUE TITLE
support for .tpp

### ISSUE THREAD

**Issue by MultiCoreNop** [jakemason/ouroboros#14]
Would it be possible to also support the .tpp extension for template files? I often have projects where template implementations are in a .tpp (which is included in the .h/.hpp at its end). Sometimes there is also a .hpp, .tpp and .cpp, but I would be fine, if switching would be tpp->hpp->cpp->hpp and in the case where there is only a .tpp and a .hpp it would do what one would expect.
Otherwise this extension is great and my new a.vim! :)

**Comment by MultiCoreNop** [comment]
While I think about it: it would be nice, if the extensions were simply taken from the config like
```lua
    extension_preferences_table = {
        c = {h = 2, hpp = 1},
        h = {c = 2, cpp = 1},
        cpp = {hpp = 2, h = 1},
        hpp = {cpp = 2, c = 2},
        tpp = {hpp = 2, h = 1},
        inl = {cpp = 3, hpp = 2, h = 1},
        cu = {cuh = 3, hpp = 2, h = 1},
        cuh = {cu = 1}
    },
```

**Comment by MultiCoreNop** [comment]
After some digging I found that my request is invalid, as this is already implemented.

As a reference for others that might hit the same bump:

This plugin gets auto-loaded for "filetype" "c" and "cpp", Therefore the command is not available in a buffer of filetype "cuda". "tpp" is not a recognized extension for NeoVim by default. To make .tpp become "filetype=cpp" add

```lua
vim.api.nvim_create_autocmd({"BufRead", "BufNewFile"}, {
    pattern = "*.tpp",
    callback = function() vim.bo.filetype = "cpp" end
})
```

somewhere in your main config. Now, to make this plugin also work with CUDA files this is the config (for Lazy) that I use:

```lua
return {
    {
        "jakemason/ouroboros.nvim",
        dependencies = {
            "nvim-lua/plenary.nvim",
        },
        config = function()
            -- these are the defaults, customize as desired
            require('ouroboros').setup({
                extension_preferences_table = {
                    c = {h = 2, hpp = 1},
                    h = {c = 4, cpp = 3, cu = 2, tpp = 1},
                    cpp = {hpp = 2, h = 1},
                    hpp = {cpp = 2, c = 3, tpp = 1},
                    tpp = {hpp = 2, h = 1},
                    inl = {cpp = 3, hpp = 2, h = 1},
                    cu = {cuh = 3, hpp = 2, h = 1},
                    cuh = {cu = 1}
                },
                -- if this is true and the matching file is already open in a pane, we'll
                -- switch to that pane instead of opening it in the current buffer
                switch_to_open_pane_if_possible = false,
            })
            vim.api.nvim_create_user_command('A', function()
                vim.cmd('Ouroboros')
            end, {})
            vim.api.nvim_create_autocmd("FileType", {
                pattern = "cuda",
                callback = function()
                    vim.api.nvim_buf_create_user_command(
                        0,
                        'Ouroboros',
                        function()
                            require('ouroboros').switch()
                        end,
                        {nargs = 0}
                    )
                end,
            })
        end
    },
}
```

This makes the command available for CUDA files as well (and defines `:A`) as a shortcut command.

**Comment by jakemason** [comment]
Sorry for the late response, I've been super busy. I'm glad you got it figured out and saw that we now support this! I'll update the README to better reflect this functionality. Thank you very much for raising the issue!

**Comment by MultiCoreNop** [comment]
No worries. Thanks for the reply! Feel free to copy&paste anything you might find useful.
