### ISSUE TITLE
consider using tables to match the file extention

### ISSUE THREAD

**Issue by mike325** [jakemason/ouroboros#2]
using tables to store valid extensions and their corresponding alternates may be easier to scale and require less changes into the code to add new options

```lua
if((extension ~= "cpp") and (extension ~= "hpp") and
   (extension ~= "c") and (extension ~= "h") and
   (extension ~= "cc")) then
    utils.log("Ouroboros doesn't work on a file ending in: ." .. extension .. ". Aborting.")
       return
end

if(extension == "cpp" or extension == "hpp") then
    desired_extension = utils.ternary(extension == "cpp", "hpp", "cpp") 
elseif(extension == "c" or extension == "h") then
    desired_extension = utils.ternary(extension == "c", "h", "c")
elseif(extension == "cc") then
    desired_extension = "h"
end       

-- vs

local extensions = {}
local c_cpp_exts_list = {
  cpp = {
    sources = {'cpp', 'C', 'cxx'},
    header = {'hpp', 'hxx'},
  },
  c = {
    sources = {'c', 'cc'},
    headers = {'h'},
  },
}

for ft, exts in pairs(c_cpp_exts) do
  for _, i in ipairs(exts.sources) do
    extentions[i] = exts.headers
  end
  for _, i in ipairs(exts.headers) do
    extentions[i] = exts.sources
  end
end

if not extensions[extension] then
    utils.log("Ouroboros doesn't work on a file ending in: ." .. extension .. ". Aborting.")
    return
end

desired_extension = extensions[extension]
```

This may even help to extend support to other languages that also have header/implementation structures like Objective-C/Objective-C++

**Comment by jakemason** [comment]
Yeah, this is a good idea and something I hadn't considered because:

1. I didn't think that this might be useful outside of C/C++
2. I didn't realize C/C++ has so many "valid" file endings.

For my own reference, later on:

https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html

**Comment by jakemason** [comment]
I just added support for this in the latest merge. Here's the relevant part of the updated README:

---
Then you can set custom weights for file extension preference matching if you'd like:
```lua
require('ouroboros').setup({
    -- these are the defaults
    extension_preferences_table = {
          c = {h = 2, hpp = 1},
          h = {c = 2, cpp = 1},
          cpp = {hpp = 2, h = 1},
          hpp = {cpp = 1, c = 2},
    }
})
```
If you don't the defaults above will be used anyway. Thus, according to the table above, a file ending in ".c" will first look for a file ending in ".h" (weight of 2) before it looks for a match of ".hpp" (weight of 1).
