### ISSUE TITLE
Create file if not exists

### ISSUE THREAD

**Issue by podratz** [jakemason/ouroboros#3]
It would be nice if you were asked to create a file/open an empty buffer if the header file can't be found.
What do you think? Does that make sense? Thanks!

**Comment by jakemason** [comment]
Yeah, this is a good request and one I need for myself. I'll probably work on this in the near future and ping you here when I have an update out.

**Comment by jakemason** [comment]
Okay, I just pushed an update for this in https://github.com/jakemason/ouroboros.nvim/commit/18f269d45ce21091ac3aa0ba2eb81c8675e74f6f. Let me know if that doesn't work for you or if you have suggestions on how to improve it.

**Comment by podratz** [comment]
Wow, super cool! I'll give it a try later. :)

**Comment by jakemason** [comment]
I'm going to close this one out now, but feel free to respond again if you have any questions or feedback on the feature! Thanks for suggesting it -- gave me the push I needed to implement it :)

Cheers,
Jake
