### ISSUE TITLE
Remove ./ if in same directory

### ISSUE THREAD

**Issue by podratz** [jakemason/ouroboros#4]
It would look a bit cleaner if the file path of the second file was displayed in the same path format as the first one.
What I mean is that when I open a few files `nvim -O {a,b,c}.hpp` their paths in the status bar are displayed simply as `a.hpp`, while the belonging cpp file's path gets displayed as `./a.cpp`. 

My mapping is this:
`vim.keymap.set('n', '<C-h>', ':Ouroboros<CR>', { silent = true })`

**Comment by jakemason** [comment]
Can you what the folder structure looks like when this happens?

Mine doesn't include the "./" in either the .hpp or the .cpp files. Could be a config in my vim file that I don't remember setting though so I'll investigate more soon...

**Comment by podratz** [comment]
They are in the same folder `src/file.{cpp,hpp}` with my working directory being `src`.

**Comment by jakemason** [comment]
I can't seem to replicate this. Here's my structure:

![Screenshot 2023-07-20 114208](https://github.com/jakemason/ouroboros.nvim/assets/12981369/03b3f55c-8090-49fc-b233-9f148bab2e3e)

And here's what happens when I repeatedly invoke Ouroboros:


https://github.com/jakemason/ouroboros.nvim/assets/12981369/28248c96-cf0e-4b53-91d4-91ebff1a9e87

**Comment by podratz** [comment]
![ezgif-5-e972a3933e](https://github.com/jakemason/ouroboros.nvim/assets/9204927/4db8211a-26ba-4241-9f01-5cb9b549e9e0)

This is how it looks on my end

**Comment by jakemason** [comment]
So I _think_ this isn't related to this plugin, but rather to individual status bar configurations.

All that this plugin does is find a matching file and then execute ```:edit {filename}```... what happens if you do ```:edit``` and pick the alternate file yourself? Do you still see the relative path "./" in your status bar?

**Comment by jakemason** [comment]
Haven't heard back on this so I'm closing it as resolved. Let me know if you do have further concerns and we can look at this again, but I think this is just a status bar configuration and not related to Ouroboros' functionality.

Cheers,
Jake
