### ISSUE TITLE
opening in a split plane?

### ISSUE THREAD

**Issue by lukerip** [jakemason/ouroboros#5]
Hi,
Thank you for building this. Is there any way to open the .h/.cc file in a split plane, instead of having a buffer be opened on top? Thanks!

**Comment by jakemason** [comment]
Hi,

Does the section in the README about splits work for this?:

----
If you'd like to open the result in a split, simply pipe Ouroboros to vsplit or split:

```vim
autocmd! Filetype c,cpp noremap<buffer> <leader>sv :vsplit \| Ouroboros<CR> " open result in a vertical split
autocmd! Filetype c,cpp noremap<buffer> <leader>sh :split \| Ouroboros<CR>  " open result in a horizontal split
```
----

You can use your own keybindings but the idea is the same, just pipe the Ouroboros command to the split command you prefer.

Let me know if this doesn't work and is about something else!

Thanks,
Jake

**Comment by lukerip** [comment]
great thanks!

**Comment by lukerip** [comment]
(sorry i should have RTFM)

**Comment by jakemason** [comment]
No worries, we've all done it before :)
