### ISSUE TITLE
Make switching smarter after split/vsplit.

### ISSUE THREAD

**Issue by ActivexDiamond** [jakemason/ouroboros#6]
Currently if you open in a split, and choose to keep that around, Ouroboros can't help you anymore. You'd have to manually navigate your open buffers.

It would be nice if you add a command which:
- Searches through open buffer.
- If a matching .h/.c/etc... is found, switch to that buffer.
- Otherwise, just do the current `:Ouroboros` does.

So basically if I already have a split open with my corresponding header/source, it'll switch to that.

**Comment by jakemason** [comment]
I believe I just added support for this in #12. Give it a try and let me know if you have further questions or requests! Thanks!
