### ISSUE TITLE
Incorrect switching with identical files in different directories

### ISSUE THREAD

**Issue by dix75** [jakemason/ouroboros#8]
Hi
I have a project that contains in two different folders, the same files.
The plugin does not switch correctly between *.h and *.cpp if another file was opened earlier.
For example

folder1/rtsp.h
folder1/rtsp.cpp

folder2/rtsp.h
folder2/rtsp.cpp

If I open folder1/rtsp.h then switch to folder1/rtsp.cpp (:Ouroboros) it works correctly, then I open folder2/rtsp.h and try to switch (:Ouroboros), the switch will be to the earlier opened buffer ( folder1/rtsp.cpp).

**Comment by jakemason** [comment]
Confirmed this is an issue. I'll take a look at some point, but it might be a while as I've been really busy (hence my 4-month later reply here)... PRs always welcome :)

Thanks for reporting it!

**Comment by jakemason** [comment]
I believe I just fixed this in the latest merge. Please let me know if you still encounter problems!
